# Workflow that should run on pushes to non-default branches, for Python
# * Lints, tests, and builds dev containers with branch changes

name: Branch CI (Python)
run-name: Branch CI for ${{ github.ref_name }} by ${{ github.actor }}

on:
  workflow_call:
    inputs:
      containerfile:
        description: >
          Path to the containerfile for building the image.
          Pass 'None' to skip building.
        default: 'Dockerfile'
        required: false
        type: string
      enable_linting:
        description: >
          Whether to run linting against the repository
          (requires ruff in the `dev` dependency group)
        default: true
        required: false
        type: boolean
      enable_typechecking:
        description: >
          Whether to typecheck the repository
          (requires mypy in the `dev` dependency group)
        default: true
        required: false
        type: boolean
      tests_folder:
        description: 'Folder to search for tests in'
        default: 'src/tests'
        required: false
        type: string
      tests_runner:
        description: >
          Which test runner to use (`pytest` or `unittest`)
          Pass 'None' to skip testing
        default: 'pytest'
        required: false
        type: string
      tests_conda_deps:
        description: >
          Any binaries required to be installed by conda for the tests to run
          (seperated by spaces e.g. `cfgrib esmpy`)
        default: ''
        required: false
        type: string
      tests_matrix:
        description: 'Whether to test against a matrix of python versions'
        default: false
        required: false
        type: boolean
      test_python_versions:
        description: 'Which python verions to use'
        default: '["3.11", "3.12"]'
        type: string
      working_directory:
        description: >
          The working directory to run the workflow in.
          Default is '.', the root of the repository.
        default: '.'
        required: false
        type: string
        
# Specify concurrency such that only one workflow can run at a time
# * Different workflow files are not affected
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Registry for storing Container images
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Job to run a linter and typechecker against the codebase
  lint-typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup uv
        uses: astral-sh/setup-uv@f0ec1fc3b38f5e7cd731bb6ce540c5af426746bb # v6.1.0
        with:
          version: "0.6.5"
          enable-cache: true
          prune-cache: false

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version-file: "${{ inputs.working_directory }}/pyproject.toml"

      - name: Install editable package and required dependencies
        if: ${{ inputs.enable_linting || inputs.enable_typechecking }}
        working-directory: ${{ inputs.working_directory }}
        run: uv sync

      - name: Lint package
        if: ${{ inputs.enable_linting }}
        working-directory: ${{ inputs.working_directory }}
        run: |
          uv run --with ruff ruff check --output-format=github .

      - name: Typecheck package
        if: ${{ inputs.enable_typechecking }}
        working-directory: ${{ inputs.working_directory }}
        run: uv run mypy .
        # TODO: GitHub output when https://github.com/python/mypy/pull/17771 merged

  create-test-matrix:
    runs-on: ubuntu-latest
    if: ${{ inputs.tests_runner != 'None' }}
    outputs:
      versions: ${{ steps.versions.outputs.versions }}
    env:
      USE_MATRIX: ${{ inputs.tests_matrix }}
    steps:
      - name: Define Python versions matrix
        id: versions
        run: |
          if [ "$USE_MATRIX" = true ]; then
          echo 'versions=${{ inputs.test_python_versions }}' >> "$GITHUB_OUTPUT";
          else echo 'versions=["default"]' >> "$GITHUB_OUTPUT";
          fi

  # Job to run unittests
  # * Optionally installs binaries using conda
  # * Produces a JUnit XML report that can be displayed in the GitHub UI
  test-unit:
    runs-on: ubuntu-latest
    needs: ['lint-typecheck', 'create-test-matrix']
    container: quay.io/condaforge/miniforge3:latest
    if: ${{ inputs.tests_runner != 'None' }}
    strategy:
      matrix:
        version: ${{ fromJSON(needs.create-test-matrix.outputs.versions) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup uv
        uses: astral-sh/setup-uv@f0ec1fc3b38f5e7cd731bb6ce540c5af426746bb # v6.1.0
        with:
          enable-cache: true
          cache-dependency-glob: "${{ inputs.working_directory }}/pyproject.toml"
          version: "0.6.5"
          python-version: ${{ matrix.version == 'default' && '' || matrix.version }}

      - name: Set up Python
        if: ${{ matrix.version == 'default' }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        id: setup-py
        with:
          python-version-file: "${{ inputs.working_directory }}/pyproject.toml"

      - name: Install conda requirements
        if: ${{ inputs.tests_conda_deps }} # An empty string evaluates to false
        working-directory: ${{ inputs.working_directory }}
        env:
          PYTHON_VERSION: ${{ matrix.version == 'default' && steps.setup-py.outputs.python-version || matrix.version }}
        run: >
          conda create --quiet --yes -p .venv 
          python=${PYTHON_VERSION%.*}
          ${{ inputs.tests_conda_deps }}

      - name: Install editable package and required dependencies
        working-directory: ${{ inputs.working_directory }}
        run: uv sync --inexact

      # Run unittests
      # * Produce JUnit XML report
      # * TODO: Work out how to pass environment variables to test
      - name: Run unit tests (with pytest)
        working-directory: ${{ inputs.working_directory }}
        if: ${{ inputs.tests_runner != 'unittest' }}
        run: uv run python -m pytest --junitxml=ut-report.xml ${{ inputs.tests_folder }}
      - name: Run unit tests (with unittest)
        working-directory: ${{ inputs.working_directory }}
        if: ${{ inputs.tests_runner == 'unittest' }}
        run: uv run python -m xmlrunner discover -s ${{ inputs.tests_folder }} -p "test_*.py" --output-file ut-report.xml

      # Create test summary to be visualised on the job summary screen on GitHub
      # * Runs even if previous steps fail
      - name: Create test summary
        uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86 # v2.4.0
        with:
          paths: "*t-report.xml"
          show: "fail, skip"
        if: always()

  # Job for building container image
  # * Builds and pushes an OCI Container image to the registry defined in the environment variables
  # * Only runs if test and lint jobs pass
  build-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: ["lint-typecheck", "test-unit"]
    if: ${{ inputs.containerfile != 'None' && github.repository_owner == 'openclimatefix' && github.event_name != 'pull_request' }}

    steps:
      # Do a non-shallow clone of the repo to ensure tags are present
      # * This allows setuptools-git-versioning to automatically set the version
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Log in to the Container registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Tag the built image according to the event type
      # The event is a branch commit, so use the commit sha
      - name: Extract metadata (tags, labels) for Container
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=ref,event=branch

      # Build and push the Container image to the registry
      # * Creates a multiplatform-aware image
      # * Pulls build cache from the registry
      - name: Build and push container image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          file: ${{ inputs.containerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
