# Bump the version of the repo and push the new version in a new commit.

name: Bump version

on:
  workflow_call:
    outputs:
      new_ver:
        description: New version number
        value: ${{ jobs.bump-version.outputs.new_ver }}
    secrets:
      PAT_TOKEN:
        required: true


jobs:
  bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    outputs:
      new_ver: ${{ steps.bumper.outputs.newTag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Bump version and push tag
        id: bumper
        uses: jasonamyers/github-bumpversion-action@v1.0.5

        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          commit-message: 'CI: bumps version to {{version}} [skip ci]'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          tags: true


